import { randomUUID } from 'node:crypto';

/**
 * X-Request-Id: "Unique request/correlation identifier generated by the caller."
 * The guide's example uses uuid4 (`str(uuid.uuid4())`), and the integration checklist says to generate a
 * fresh ID for EVERY call. `crypto.randomUUID()` produces an RFC 4122 version-4 UUID.
 */
export function newRequestId(): string {
  return randomUUID();
}

const UUID_V4 = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export function isUuidV4(value: string): boolean {
  return UUID_V4.test(value);
}
