import { randomUUID } from 'node:crypto';

/**
 * X-Request-Id: "Unique request/correlation identifier generated by the caller."
 * The guide's example uses uuid4 (`str(uuid.uuid4())`), and the integration checklist says to generate a
 * fresh ID for EVERY call. `crypto.randomUUID()` produces an RFC 4122 version-4 UUID.
 */
export function newRequestId(): string {
  return randomUUID();
}
