/**
 * Static catalog: what the suite is DESIGNED to test, derived from the PII Service API Integration Guide
 * and the test suite (docs/requirements-traceability.md, docs/test-scenarios.md).
 *
 * This is knowledge about test DESIGN, never about results. Results always come from executed runs.
 * Test references are display IDs ("PII-WR-001") or prefix patterns ("PII-NRM-*").
 */
import type { AreaInfo, AreaKey, Requirement, Severity, TestRef } from './types';

export const AREAS: AreaInfo[] = [
  {
    key: 'health',
    label: 'Health',
    description: 'Service readiness endpoint',
    severity: 'low',
    security: false,
    db: false,
  },
  {
    key: 'contract',
    label: 'Contract',
    description: 'OpenAPI drift and exact response keys',
    severity: 'medium',
    security: false,
    db: false,
  },
  {
    key: 'write',
    label: 'PII Write',
    description: 'Create / replace (upsert) PII fields',
    severity: 'high',
    security: false,
    db: false,
  },
  {
    key: 'read',
    label: 'PII Read',
    description: 'Read selected fields for one user',
    severity: 'high',
    security: false,
    db: false,
  },
  {
    key: 'search',
    label: 'Search',
    description: 'Exact normalized search',
    severity: 'medium',
    security: false,
    db: false,
  },
  {
    key: 'batch',
    label: 'Batch Read',
    description: 'Users × fields set-based read',
    severity: 'medium',
    security: false,
    db: false,
  },
  {
    key: 'normalization',
    label: 'Normalization',
    description: 'Email, phone and name normalization',
    severity: 'medium',
    security: false,
    db: false,
  },
  {
    key: 'transient',
    label: 'Transient Phone',
    description: 'Create / resolve / promote temporary phone mappings',
    severity: 'high',
    security: false,
    db: false,
  },
  {
    key: 'freeText',
    label: 'Free-Text Keys',
    description: 'AES-256-GCM key create / read / revoke',
    severity: 'high',
    security: false,
    db: false,
  },
  {
    key: 'authentication',
    label: 'Authentication',
    description: 'Ed25519 request signing and body integrity',
    severity: 'critical',
    security: true,
    db: false,
  },
  {
    key: 'authorization',
    label: 'Authorization',
    description: 'Per-field READ / WRITE / SEARCH / BULK_READ',
    severity: 'critical',
    security: true,
    db: false,
  },
  {
    key: 'tenantIsolation',
    label: 'Tenant Isolation',
    description: '(tenant, user) identity separation',
    severity: 'critical',
    security: true,
    db: false,
  },
  {
    key: 'responseSecurity',
    label: 'Response Security',
    description: 'Leak checks, body limits, dev helpers',
    severity: 'critical',
    security: true,
    db: false,
  },
  {
    key: 'database',
    label: 'Database',
    description: 'Read-only persistence & encryption-at-rest checks',
    severity: 'critical',
    security: true,
    db: true,
  },
  {
    key: 'poc',
    label: 'End-to-end POC',
    description: 'Write → DB → Read proof of concept',
    severity: 'critical',
    security: true,
    db: true,
  },
  {
    key: 'framework',
    label: 'Framework Self-tests',
    description: 'Signer, client wire, redaction, config (no service)',
    severity: 'low',
    security: false,
    db: false,
  },
  {
    key: 'other',
    label: 'Other',
    description: 'Tests without a recognised ID prefix',
    severity: 'medium',
    security: false,
    db: false,
  },
];

const PREFIX_TO_AREA: [RegExp, AreaKey][] = [
  [/^PII-HLT-/, 'health'],
  [/^PII-CON-/, 'contract'],
  [/^PII-WR-/, 'write'],
  [/^PII-RD-/, 'read'],
  [/^PII-SR-/, 'search'],
  [/^PII-BR-/, 'batch'],
  [/^PII-NRM-/, 'normalization'],
  [/^PII-TR-/, 'transient'],
  [/^PII-FT-/, 'freeText'],
  [/^PII-AUTH-/, 'authentication'],
  [/^PII-AZ-/, 'authorization'],
  [/^PII-TI-/, 'tenantIsolation'],
  [/^PII-SEC-/, 'responseSecurity'],
  [/^PII-DB-/, 'database'],
  [/^POC-/, 'poc'],
  [/^UT-/, 'framework'],
];

export function areaForId(id: string): AreaKey {
  return PREFIX_TO_AREA.find(([re]) => re.test(id))?.[1] ?? 'other';
}

export function areaInfo(key: AreaKey): AreaInfo {
  return AREAS.find((a) => a.key === key) ?? (AREAS[AREAS.length - 1] as AreaInfo);
}

export function severityFor(area: AreaKey): Severity {
  return areaInfo(area).severity;
}

// ---- Endpoint under test per test ID ----------------------------------------------------------------

const ALL_AUTHENTICATED = [
  'writePii',
  'readPii',
  'searchPii',
  'batchReadPii',
  'createTransientPhone',
  'resolveTransientPhone',
  'promoteTransientPhone',
  'createFreeTextKey',
  'readFreeTextKey',
  'revokeFreeTextKey',
];

const AREA_DEFAULT_ENDPOINTS: Partial<Record<AreaKey, string[]>> = {
  health: ['healthReady'],
  write: ['writePii'],
  read: ['readPii'],
  search: ['searchPii'],
  batch: ['batchReadPii'],
  normalization: ['writePii', 'readPii'],
  authentication: ['writePii'],
  poc: ['writePii', 'readPii'],
};

const T = { c: 'createTransientPhone', r: 'resolveTransientPhone', p: 'promoteTransientPhone' };
const K = { c: 'createFreeTextKey', r: 'readFreeTextKey', v: 'revokeFreeTextKey' };

const ENDPOINT_OVERRIDES: Record<string, string[]> = {
  'PII-CON-001': [],
  'PII-CON-002': [],
  'PII-CON-003': ['writePii', 'readPii', 'searchPii', 'batchReadPii'],
  'PII-CON-004': [T.c, T.r, T.p],
  'PII-CON-005': [K.c, K.r, K.v],
  'PII-TR-001': [T.c],
  'PII-TR-002': [T.r],
  'PII-TR-003': [T.r, T.p],
  'PII-TR-004': [T.r, T.p],
  'PII-TR-005': [T.r, T.p],
  'PII-TR-006': [T.p, T.r],
  'PII-TR-007': [T.p],
  'PII-TR-008': [T.c],
  'PII-TR-009': [T.c],
  'PII-TR-010': [T.c],
  'PII-TR-011': [T.c],
  'PII-TR-012': [T.r, T.p],
  'PII-FT-001': [K.c],
  'PII-FT-002': [K.r],
  'PII-FT-003': [K.v, K.r],
  'PII-FT-004': [K.v],
  'PII-FT-005': [K.r, K.v],
  'PII-FT-006': [K.r, K.v],
  'PII-FT-007': [K.r, K.c],
  'PII-FT-008': [K.c],
  'PII-FT-009': [K.c],
  'PII-FT-010': [K.c, K.r],
  'PII-AUTH-020': ALL_AUTHENTICATED,
  'PII-AZ-001': ['writePii'],
  'PII-AZ-002': ['readPii'],
  'PII-AZ-003': ['readPii'],
  'PII-AZ-004': ['readPii'],
  'PII-AZ-005': ['searchPii'],
  'PII-AZ-006': ['searchPii'],
  'PII-AZ-007': ['searchPii'],
  'PII-AZ-008': ['batchReadPii'],
  'PII-AZ-009': [T.c, T.p],
  'PII-AZ-010': [T.r],
  'PII-AZ-011': [K.c, K.r, K.v],
  'PII-AZ-012': ['readPii'],
  'PII-TI-001': ['writePii', 'readPii'],
  'PII-TI-002': ['readPii'],
  'PII-TI-003': ['searchPii'],
  'PII-TI-004': ['batchReadPii'],
  'PII-TI-005': ['writePii', 'readPii'],
  'PII-TI-006': ['readPii'],
  'PII-SEC-001': ['writePii'],
  'PII-SEC-002': ['writePii'],
  'PII-SEC-003': [],
  'PII-SEC-004': ['writePii', 'readPii', 'searchPii', T.c, T.r, K.c],
  'PII-DB-001': ['writePii'],
  'PII-DB-002': ['writePii'],
  'PII-DB-003': ['writePii'],
  'PII-DB-004': ['writePii'],
  'PII-DB-005': [T.c, T.p],
  'PII-DB-006': [K.c, K.v],
  'PII-DB-007': ['batchReadPii'],
};

export function endpointsForId(id: string, area: AreaKey): string[] {
  return ENDPOINT_OVERRIDES[id] ?? AREA_DEFAULT_ENDPOINTS[area] ?? [];
}

/** Resolve a TestRef against a set of known IDs. */
export function matchesRef(id: string, ref: TestRef): boolean {
  return ref.endsWith('*') ? id.startsWith(ref.slice(0, -1)) : id === ref;
}

// ---- Requirements (machine-readable version of docs/requirements-traceability.md) --------------------

const req = (
  id: string,
  group: string,
  title: string,
  type: Requirement['type'],
  source: string,
  endpoints: string[],
  tests: TestRef[],
  openQuestion?: string,
): Requirement => ({
  id,
  group,
  title,
  type,
  source,
  endpoints,
  tests,
  ...(openQuestion ? { openQuestion } : {}),
});

export const REQUIREMENTS: Requirement[] = [
  req(
    'R-AUTH-01',
    'Authentication',
    'Every /api/v1 request requires an Ed25519 signature',
    'Documented',
    'Authentication',
    ALL_AUTHENTICATED,
    ['PII-AUTH-016', 'PII-AUTH-020'],
  ),
  req(
    'R-AUTH-02',
    'Authentication',
    'Signature = Base64(Ed25519(SHA-256(exact body bytes)))',
    'Documented',
    'Signature calculation',
    ['writePii'],
    ['UT-SIG-*', 'UT-CLI-001', 'PII-AUTH-001', 'PII-AUTH-011'],
  ),
  req(
    'R-AUTH-03',
    'Authentication',
    'Signed bytes must exactly match transmitted bytes',
    'Documented',
    'Signature calculation',
    ['writePii'],
    ['UT-SIG-007', 'UT-CLI-001', 'UT-CLI-007', 'PII-AUTH-008', 'PII-AUTH-009', 'PII-AUTH-010'],
  ),
  req(
    'R-AUTH-04',
    'Authentication',
    'Required headers: Content-Type, Caller-Id, Request-Id, Signature',
    'Documented',
    'Authentication',
    ['writePii'],
    ['UT-CLI-002', 'PII-AUTH-002', 'PII-AUTH-012', 'PII-AUTH-015', 'PII-AUTH-018'],
    'Q-13',
  ),
  req(
    'R-AUTH-05',
    'Authentication',
    'Public key is bound to the caller ID',
    'Derived',
    'Authentication',
    ['writePii'],
    ['PII-AUTH-007', 'PII-AUTH-017', 'UT-SIG-008'],
  ),
  req(
    'R-AUTH-06',
    'Authentication',
    'Invalid headers/caller/signature → 401',
    'Documented',
    'Common statuses',
    ['writePii'],
    ['PII-AUTH-*', 'PII-DB-004'],
    'Q-06',
  ),
  req(
    'R-AUTH-07',
    'Authentication',
    'Rejected requests are not processed',
    'Derived',
    'Authentication',
    ['writePii'],
    ['PII-AUTH-002', 'PII-AUTH-008', 'PII-DB-004'],
  ),
  req(
    'R-AUTH-08',
    'Authentication',
    'Fresh X-Request-Id per call',
    'Documented',
    'Checklist 6',
    [],
    ['UT-CLI-003', 'UT-CLI-009'],
  ),
  req(
    'R-AUTH-09',
    'Authentication',
    '401 and 403 treated differently; not retried',
    'Documented',
    'Checklist 8',
    ['writePii', 'readPii'],
    ['PII-AUTH-019', 'PII-AZ-012', 'UT-CLI-010'],
  ),
  req(
    'R-AUTH-10',
    'Authentication',
    'Reused request ID behaviour',
    'Derived',
    'Checklist 6',
    [],
    ['PII-AUTH-021'],
    'Q-14',
  ),
  req(
    'R-AUTH-11',
    'Authentication',
    'Replay protection',
    'Derived',
    'Authentication',
    [],
    ['PII-AUTH-022'],
    'Q-21',
  ),
  req(
    'R-AZ-01',
    'Authorization',
    'Missing field permission → 403 AUTHORIZATION_DENIED',
    'Documented',
    'Field authorization',
    ['writePii', 'readPii', 'searchPii', 'batchReadPii'],
    ['PII-AZ-001', 'PII-AZ-002', 'PII-AZ-007', 'PII-AZ-008'],
  ),
  req(
    'R-AZ-02',
    'Authorization',
    'Read requires READ for every requested field',
    'Documented',
    '§3 Read PII',
    ['readPii'],
    ['PII-AZ-003', 'PII-AZ-004'],
  ),
  req(
    'R-AZ-03',
    'Authorization',
    'Search requires SEARCH; include_values also READ',
    'Documented',
    '§4 Search PII',
    ['searchPii'],
    ['PII-AZ-005', 'PII-AZ-006', 'PII-AZ-007'],
  ),
  req(
    'R-AZ-04',
    'Authorization',
    'Batch requires BULK_READ for every field',
    'Documented',
    '§5 Batch read',
    ['batchReadPii'],
    ['PII-AZ-008'],
  ),
  req(
    'R-AZ-05',
    'Authorization',
    'Transient permissions (WRITE/READ PHONE)',
    'Documented',
    '§6–8',
    ['createTransientPhone', 'resolveTransientPhone', 'promoteTransientPhone'],
    ['PII-AZ-009', 'PII-AZ-010'],
  ),
  req(
    'R-AZ-06',
    'Authorization',
    'FREE_TEXT capability permissions',
    'Documented',
    '§9–11',
    ['createFreeTextKey', 'readFreeTextKey', 'revokeFreeTextKey'],
    ['PII-AZ-011'],
  ),
  req(
    'R-TEN-01',
    'Isolation',
    'User identity is (tenant_id, user_id)',
    'Documented',
    'Shared concepts',
    ['writePii', 'readPii'],
    ['PII-TI-001', 'PII-TI-005', 'PII-DB-003'],
  ),
  req(
    'R-TEN-02',
    'Isolation',
    'Read/search/batch restricted to requested tenant',
    'Derived',
    'Shared concepts',
    ['readPii', 'searchPii', 'batchReadPii'],
    ['PII-TI-002', 'PII-TI-003', 'PII-TI-004'],
  ),
  req(
    'R-TEN-03',
    'Isolation',
    'Tenant scopes data; authorization separate',
    'Documented',
    'Shared concepts',
    ['readPii'],
    ['PII-TI-006', 'PII-AZ-004'],
    'Q-27',
  ),
  req(
    'R-TEN-04',
    'Isolation',
    'Transient mapping owned by caller and tenant',
    'Documented',
    '§7',
    ['resolveTransientPhone', 'promoteTransientPhone'],
    ['PII-TR-003', 'PII-TR-004'],
  ),
  req(
    'R-TEN-05',
    'Isolation',
    'Free-text key owned by caller and tenant',
    'Documented',
    '§10–11',
    ['readFreeTextKey', 'revokeFreeTextKey'],
    ['PII-FT-005', 'PII-FT-006'],
  ),
  req(
    'R-WR-01',
    'PII Write',
    'Upsert: 201 new, 200 replace',
    'Documented',
    '§2',
    ['writePii'],
    ['PII-WR-001', 'PII-WR-002', 'PII-DB-001'],
  ),
  req(
    'R-WR-02',
    'PII Write',
    'Response has tenant, user, canonical field, key_version',
    'Documented',
    '§2',
    ['writePii'],
    ['PII-WR-001', 'PII-WR-003', 'PII-CON-003'],
  ),
  req(
    'R-WR-03',
    'PII Write',
    'Field name case-insensitive, stored uppercase',
    'Documented',
    '§2',
    ['writePii'],
    ['PII-WR-003'],
  ),
  req(
    'R-WR-04',
    'PII Write',
    'Field length constraints',
    'Documented',
    '§2',
    ['writePii'],
    ['PII-WR-005', 'PII-WR-005b', 'PII-WR-006', 'PII-WR-007'],
  ),
  req(
    'R-WR-05',
    'PII Write',
    'Malformed / missing / wrong-typed JSON → 422',
    'Documented',
    'Common statuses',
    ['writePii'],
    ['PII-WR-004', 'PII-WR-011', 'PII-WR-012'],
    'Q-05',
  ),
  req(
    'R-WR-06',
    'PII Write',
    'Invalid email/phone → 400 VALIDATION_ERROR',
    'Documented',
    'Common statuses',
    ['writePii', 'createTransientPhone'],
    ['PII-WR-008', 'PII-WR-009', 'PII-TR-010'],
  ),
  req(
    'R-WR-07',
    'PII Write',
    'Unsupported field rejected',
    'Derived',
    '§2',
    ['writePii'],
    ['PII-WR-010'],
    'Q-07',
  ),
  req(
    'R-RD-01',
    'PII Read',
    'Selected fields; missing omitted; 404 if none',
    'Documented',
    '§3',
    ['readPii'],
    ['PII-RD-001', 'PII-RD-002', 'PII-RD-003', 'PII-RD-004', 'PII-RD-005', 'PII-RD-006'],
  ),
  req(
    'R-RD-02',
    'PII Read',
    'field_names must be non-empty',
    'Documented',
    '§3',
    ['readPii'],
    ['PII-RD-007', 'PII-RD-008'],
  ),
  req(
    'R-RD-03',
    'PII Read',
    'Read response contract',
    'Documented',
    '§3',
    ['readPii'],
    ['PII-RD-009', 'PII-CON-003'],
  ),
  req(
    'R-SR-01',
    'Search',
    'Exact match after normalization',
    'Documented',
    '§4',
    ['searchPii'],
    ['PII-SR-001', 'PII-SR-002', 'PII-SR-003'],
  ),
  req(
    'R-SR-02',
    'Search',
    'include_values=false returns user IDs only',
    'Documented',
    '§4',
    ['searchPii'],
    ['PII-SR-001', 'UT-AST-003', 'PII-CON-003'],
  ),
  req(
    'R-SR-03',
    'Search',
    'include_values=true returns values',
    'Documented',
    '§4',
    ['searchPii'],
    ['PII-SR-010'],
  ),
  req(
    'R-SR-04',
    'Search',
    'limit 1–100, default 10, truncated flag',
    'Documented',
    '§4',
    ['searchPii'],
    ['PII-SR-006', 'PII-SR-007', 'PII-SR-008', 'PII-SR-009'],
    'Q-09',
  ),
  req(
    'R-SR-05',
    'Search',
    'Only searchable fields may be searched',
    'Documented',
    '§4',
    ['searchPii'],
    ['PII-SR-012'],
    'Q-18',
  ),
  req('R-SR-06', 'Search', 'No-match behaviour', 'Derived', '§4', ['searchPii'], ['PII-SR-004'], 'Q-08'),
  req(
    'R-BR-01',
    'Batch',
    'Cartesian product users × fields',
    'Documented',
    '§5',
    ['batchReadPii'],
    ['PII-BR-001'],
  ),
  req(
    'R-BR-02',
    'Batch',
    'Item count ≤ batch_max_items',
    'Documented',
    '§5',
    ['batchReadPii'],
    ['PII-BR-004', 'PII-BR-005'],
    'Q-19',
  ),
  req(
    'R-BR-03',
    'Batch',
    'user_ids 1–200, fields 1–64',
    'Documented',
    '§5',
    ['batchReadPii'],
    ['PII-BR-007'],
  ),
  req(
    'R-BR-04',
    'Batch',
    'Duplicate pairs de-duplicated',
    'Documented',
    '§5',
    ['batchReadPii'],
    ['PII-BR-006'],
    'Q-20',
  ),
  req(
    'R-BR-05',
    'Batch',
    'Missing omitted; user with none → 404',
    'Documented',
    '§5',
    ['batchReadPii'],
    ['PII-BR-002', 'PII-BR-003'],
  ),
  req(
    'R-BR-06',
    'Batch',
    'One PII_BATCH_READ audit event',
    'Documented',
    '§5',
    ['batchReadPii'],
    ['PII-DB-007'],
    'Q-26',
  ),
  req(
    'R-NRM-01',
    'Normalization',
    'Email trimmed + lowercased; must contain @',
    'Documented',
    'Value normalization',
    ['writePii'],
    ['PII-NRM-001', 'PII-NRM-005', 'PII-WR-008', 'PII-SR-002', 'POC-001'],
  ),
  req(
    'R-NRM-02',
    'Normalization',
    'Phone digits only, 8–15 digits',
    'Documented',
    'Value normalization',
    ['writePii', 'createTransientPhone'],
    ['PII-NRM-002', 'PII-NRM-004', 'PII-WR-009', 'PII-TR-002'],
  ),
  req(
    'R-NRM-03',
    'Normalization',
    'Text trimmed, whitespace collapsed',
    'Documented',
    'Value normalization',
    ['writePii'],
    ['PII-NRM-003', 'PII-WR-013'],
    'Q-10',
  ),
  req(
    'R-ENC-01',
    'Encryption',
    'Values encrypted before persistence',
    'Documented',
    '§2',
    ['writePii'],
    ['POC-001', 'PII-DB-001', 'PII-DB-002'],
    'Q-03',
  ),
  req(
    'R-ENC-02',
    'Encryption',
    'key_version is the DEK version used',
    'Documented',
    '§2',
    ['writePii'],
    ['POC-001', 'PII-DB-001'],
    'Q-16',
  ),
  req(
    'R-ENC-03',
    'Encryption',
    'Record bound to correct tenant/user; one row per field',
    'Derived',
    '§2',
    ['writePii'],
    ['POC-001', 'PII-DB-001', 'PII-DB-003'],
  ),
  req(
    'R-ENC-04',
    'Encryption',
    'Transient phone encrypted; consumed on promote',
    'Documented',
    '§6, §8',
    ['createTransientPhone', 'promoteTransientPhone'],
    ['PII-DB-005', 'PII-TR-006'],
  ),
  req(
    'R-ENC-05',
    'Encryption',
    'Free-text key is 256-bit AES-256-GCM',
    'Documented',
    '§9',
    ['createFreeTextKey'],
    ['PII-FT-001', 'PII-FT-009', 'UT-AST-010'],
  ),
  req(
    'R-ENC-06',
    'Encryption',
    'Revoked keys have REVOKED state',
    'Documented',
    '§11',
    ['revokeFreeTextKey'],
    ['PII-FT-003', 'PII-DB-006'],
  ),
  req(
    'R-TR-01',
    'Transient',
    'Create returns transient_id + expires_at (201)',
    'Documented',
    '§6',
    ['createTransientPhone'],
    ['PII-TR-001'],
  ),
  req(
    'R-TR-02',
    'Transient',
    'TTL within configured bounds',
    'Documented',
    '§6',
    ['createTransientPhone'],
    ['PII-TR-008', 'PII-TR-009'],
    'Q-11',
  ),
  req(
    'R-TR-03',
    'Transient',
    'Resolve returns normalized phone with no-store',
    'Documented',
    '§7',
    ['resolveTransientPhone'],
    ['PII-TR-002'],
  ),
  req(
    'R-TR-04',
    'Transient',
    'Missing/expired/consumed/foreign → 404',
    'Documented',
    'Common statuses',
    ['resolveTransientPhone', 'promoteTransientPhone'],
    ['PII-TR-003', 'PII-TR-004', 'PII-TR-005', 'PII-TR-006', 'PII-TR-012'],
    'Q-12',
  ),
  req(
    'R-TR-05',
    'Transient',
    'Promote stores PHONE, consumes mapping, repeat → 404',
    'Documented',
    '§8',
    ['promoteTransientPhone'],
    ['PII-TR-006', 'PII-TR-007'],
  ),
  req(
    'R-FT-01',
    'Free-text',
    'Create key: 201, metadata, no-store',
    'Documented',
    '§9',
    ['createFreeTextKey'],
    ['PII-FT-001', 'PII-FT-008'],
  ),
  req(
    'R-FT-02',
    'Free-text',
    'Read active key with no-store',
    'Documented',
    '§10',
    ['readFreeTextKey'],
    ['PII-FT-002'],
  ),
  req(
    'R-FT-03',
    'Free-text',
    'Revoke → REVOKED; read then 404',
    'Documented',
    '§10–11',
    ['revokeFreeTextKey', 'readFreeTextKey'],
    ['PII-FT-003', 'PII-FT-004'],
  ),
  req(
    'R-FT-04',
    'Free-text',
    'Never log returned keys',
    'Documented',
    'Checklist 7',
    ['createFreeTextKey', 'readFreeTextKey'],
    ['PII-FT-010', 'UT-CLI-011', 'UT-CLI-012', 'PII-SEC-004'],
  ),
  req(
    'R-HLT-01',
    'Health',
    'Readiness 200 envelope without auth',
    'Documented',
    '§1',
    ['healthReady'],
    ['PII-HLT-001'],
  ),
  req(
    'R-HLT-02',
    'Health',
    'Not ready → 503 SERVICE_NOT_READY',
    'Documented',
    '§1',
    ['healthReady'],
    ['PII-HLT-002'],
    'Q-17',
  ),
  req(
    'R-ENV-01',
    'Contract',
    'Success / error envelope shapes',
    'Documented',
    'Shared concepts',
    ALL_AUTHENTICATED,
    ['PII-CON-003', 'PII-CON-004', 'PII-CON-005'],
  ),
  req(
    'R-ENV-02',
    'Contract',
    'OpenAPI matches documented inventory',
    'Derived',
    'Endpoint summary',
    [],
    ['PII-CON-001', 'PII-CON-002'],
    'Q-24',
  ),
  req(
    'R-SEC-01',
    'Security',
    '413 BODY_TOO_LARGE above configured max',
    'Documented',
    'Common statuses',
    ['writePii'],
    ['PII-SEC-002'],
    'Q-22',
  ),
  req(
    'R-SEC-02',
    'Security',
    '/docs/signature not exposed outside development',
    'Documented',
    'Public documentation endpoints',
    [],
    ['PII-SEC-003'],
    'Q-23',
  ),
  req(
    'R-SEC-03',
    'Security',
    'No plaintext PII, signatures, keys or bodies in logs',
    'Documented',
    'Checklist 7',
    ['writePii', 'readPii'],
    ['POC-001', 'PII-SEC-004', 'UT-RED-*', 'UT-CLI-012'],
  ),
  req(
    'R-SEC-04',
    'Security',
    'Bounded exponential backoff for 503',
    'Documented',
    'Checklist 9',
    [],
    ['UT-CLI-009', 'UT-CLI-010', 'UT-RTY-*'],
  ),
  req(
    'R-SEC-05',
    'Security',
    'Honour Cache-Control: no-store',
    'Documented',
    'Checklist 10',
    ['resolveTransientPhone', 'createFreeTextKey', 'readFreeTextKey'],
    ['PII-TR-002', 'PII-FT-001', 'PII-FT-002'],
  ),
  req(
    'R-SEC-06',
    'Security',
    'Error bodies do not echo PII',
    'Policy',
    'P-01',
    ['writePii'],
    ['PII-SEC-001'],
  ),
];

export const ENDPOINT_DESCRIPTIONS: Record<string, string> = {
  healthReady: 'Readiness check',
  writePii: 'Create or replace one PII field',
  readPii: 'Read selected PII fields for one user',
  searchPii: 'Exact normalized search on a searchable field',
  batchReadPii: 'Read fields for multiple users in one set-based query',
  createTransientPhone: 'Create a temporary encrypted phone mapping',
  resolveTransientPhone: 'Resolve an owned, unexpired mapping',
  promoteTransientPhone: 'Store a transient phone as permanent user PII',
  createFreeTextKey: 'Create a caller-owned free-text encryption key',
  readFreeTextKey: 'Retrieve an active caller-owned key',
  revokeFreeTextKey: 'Revoke a caller-owned key',
};
